### PR TITLE
Fix search pagination 9

### LINKED ISSUE #9: enable pagination on search page
from #5 

http://localhost:8081/monarch-ui/search/pax

For pagination, have to use b-table and link currentPage to both b-table and b-pagination:

https://bootstrap-vue.js.org/docs/components/table

and provide a query method

### PR DESCRIPTION
**Pull request by nathandunn**
Will fix #9

### CODE REVIEW

**Comment by nathandunn** [comment]
@DoctorBud  Ready for review

File: src/views/Search.vue [hunk 1]
```diff
@@ -21,63 +21,66 @@
                   Search Results
                 </p>
               </div>
-            </div>
+            </div>label:
```
Comment (DoctorBud) [inline src/views/Search.vue]: This `label:` looks like a typo. Please doublecheck.

File: src/views/Search.vue [hunk 2]
```diff
@@ -220,6 +241,10 @@ export default {
         clear: both;
     }
 
+    .topMargin{
```
Comment (DoctorBud) [inline src/views/Search.vue]: If you aren't familiar with BS4's spacing utility classes, you should be. Sometimes there is a class already available for things like this. So class `mt-2` or `mt-1` might fit your needs (unless 20px is exactly what you need). See https://getbootstrap.com/docs/4.1/utilities/spacing/

File: src/views/Search.vue [hunk 3]
```diff
@@ -27,57 +27,60 @@
...
+          </div>
         </div>
-      </div>
 
 
-      <footer class="footer">
-        <home-footer/>
-      </footer>
+        <footer class="footer">
+          <home-footer/>
```
Comment (DoctorBud) [inline src/views/Search.vue]: I mentioned this before somewhere (Gitter or another PR). Please use `FooterAll.vue` instead of `HomeFooter.vue`. FooterAll.vue is intended to be a thinner footer than that on the home page.

**Comment by DoctorBud** [comment]
+1
