### PR TITLE
Fix text search 5 - fixes UI

### LINKED ISSUE #5: create text search option
From #1:

Wire up the "search in all results" to give you what you get here https://alpha.monarchinitiative.org/search/marfan

- [x] crate valid biolink API call in BioLink.js
- [x] call valid BioLink.js route from Search page with id parameter specified
- [x] display in search page with route
- ~~add pagination~~ to #9 

- ~~add facets to~~ to #8 
- ~~add category structure~~ to #8

### PR DESCRIPTION
**Pull request by nathandunn**
fixes #5

### CODE REVIEW

File: src/views/Search.vue [hunk 1]
```diff
@@ -0,0 +1,251 @@
...
+                <td v-html="result.highlight"/>
+              </tr>
+            </tbody>
+          </table>
+        </div>
+      </div>
+
+
+      <footer class="footer">
+        <home-footer/>
```
Comment (DoctorBud) [inline src/views/Search.vue]: Use FooterAll.vue instead of HomeFooter.vue. Content pages will have a thinner footer. I guess we could have a parameterized Footer.vue, but right now we have 2 files. Not a blocker for this PR.

**Comment by DoctorBud** [comment]
+1 Going to merge it.
